<?php

use Magento\Framework\Escaper;
use Wexo\HeyLoyalty\Block\Tracking as TrackingBlock;
use Wexo\HeyLoyalty\ViewModel\Tracking as TrackingViewModel;

/** @var TrackingBlock $block */
/** @var Escaper $escaper */
/** @var TrackingViewModel $viewModel */
$viewModel = $block->getViewModel();
$apiKey = $viewModel->getApiKey();
$sessionTime = $viewModel->getSessionTime();
$trackingId = $viewModel->getTrackingId();
$trackingActivated = $viewModel->getIsTrackingActivated();
?>
<?= $block->getLayout()
    ->createBlock(TrackingBlock::class)
    ->setTemplate('Wexo_HeyLoyalty::tracking_script.phtml')
    ->setData('apiKey', $apiKey)
    ->setData('sessionTime', $sessionTime)
    ->setData('trackingId', $trackingId)
    ->setData('trackingActivated', $trackingActivated)
    ->toHtml(); ?>

<!-- hlt.visit(productid, categoryid, categoryname)/()/(,,categoryname) -->
<script>
    jQuery(document).ready(function() {
        <?php if (!$viewModel->isProductPage() && !$viewModel->isCategoryPage()): ?>
        window.hlt.visit();
        <?php endif; ?>
    });
</script>


<!--hlt.addToBasket(productid, productCount, categoryid, basketid, categoryname)-->
<script>
    function hltAddToBasket() {
        <?php
        $product = $block->getProduct();
        $category = $block->getCategory();
        $quoteId = $block->getQuoteId() ?? '';
        ?>
        window.hlt.addToBasket("<?= $product?->getId() ?? '' ?>", "1", "<?= $category?->getId() ?? '' ?>", "<?= $quoteId ?>", "<?= $category?->getName() ?? '' ?>");
    }
</script>

<!--hlt.removeFromBasket(productid)-->
<script>
    function hltRemoveFromBasket() {
        <?php
        $product = $block->getProduct();
        ?>
        window.hlt.removeFromBasket("<?= $product?->getId() ?? '' ?>");
    }
</script>

<!--hlt.purchasedBasket-->
<script>
    function hltPurchasedBasket() {
        window.hlt.purchasedBasket();
    }
</script>

<!--hlt.pairEmail(email)-->
<script>
    function hltPairEmail() {
        <?php
        $email = $block->getEmail() ?? '';
        ?>
        window.hlt.pairEmail("<?= $email ?>");
    }
</script>

<!--hlt.heartbeat()-->
<script>
    function hltHeartbeat() {
        window.hlt.heartbeat();
    }
</script>
