<?php

use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;
use Wexo\HeyLoyalty\Block\Tracking as TrackingBlock;
use Wexo\HeyLoyalty\ViewModel\Tracking as TrackingViewModel;

/** @var View $block */
/** @var Escaper $escaper */
/** @var TrackingViewModel $viewModel */
$viewModel = $block->getViewModel();
$apiKey = $viewModel->getApiKey();
$sessionTime = $viewModel->getSessionTime();
$trackingId = $viewModel->getTrackingId();
$trackingActivated = $viewModel->getIsTrackingActivated();
?>
<?= $block->getLayout()
    ->createBlock(TrackingBlock::class)
    ->setTemplate('Wexo_HeyLoyalty::tracking_script.phtml')
    ->setData('apiKey', $apiKey)
    ->setData('sessionTime', $sessionTime)
    ->setData('trackingId', $trackingId)
    ->setData('trackingActivated', $trackingActivated)
    ->toHtml(); ?>

<script>
    jQuery(document).ready(function() {
        <?php
        $product = $block->getProduct();
        $category = $product?->getCategory();
        ?>
        window.hlt.visit(
            "<?= $product?->getId() ?? '' ?>",
            "<?= $category?->getId() ?? '' ?>",
            "<?= $category?->getName() ?? '' ?>"
        );
    });
</script>
