<?php

use Magento\Framework\Escaper;
use Wexo\HeyLoyalty\Block\Tracking as TrackingBlock;

/** @var TrackingBlock $block */
/** @var Escaper $escaper */
$apiKey = $block->getData('apiKey');
$sessionTime = $block->getData('sessionTime');
$trackingId = $block->getData('trackingId');
$trackingActivated = $block->getData('trackingActivated');
?>
<?php if ($trackingActivated): ?>
    <script type="text/javascript">
        let BiTrackingLoaded = function (BiTracking) {
            window.hlt=BiTracking;
            BiTracking.initialize(
                "<?= $escaper->escapeHtml($apiKey) ?>",
                "<?= $escaper->escapeHtml($sessionTime) ?>",
                "<?= $escaper->escapeHtml($trackingId) ?>"
            );
        }
    </script>
    <script>
        (function (d, t) {
            let g = d.createElement(t),
                s = d.getElementsByTagName(t)[0];
            h = "https:" === document.location.protocol ? "https://" : "http://";
            g.src = h + 'bi.heyloyalty.com/hlbi.js';
            s.parentNode.insertBefore(g, s);
        }
        (document, 'script'));
    </script>
<?php endif; ?>
