<?php

use Magento\Framework\Escaper;
use Wexo\HeyLoyalty\Block\Adminhtml\System\Config\ExportButton;

/** @var ExportButton $block */
/** @var Escaper $escaper */
?>
<div class="heyloyalty_export_container">
    <a id="<?= $escaper->escapeHtml($block->getId()) ?>" href="<?= $escaper->escapeHtml($block->getControllerURL()) ?>" class="action-add" target="_heyloyalty_csv_export">
        <span><?= $escaper->escapeHtml($block->getLabel()) ?></span>
    </a>
    <br>
    <a id="<?= $escaper->escapeHtml($block->getId()) ?>_trigger" href="<?= $escaper->escapeHtml($block->getAdminControllerURL()) ?>" class="action-add">
        <span><?= __('Send to HeyLoyalty') ?></span>
    </a>
</div>
